import {expect,it,vi,afterEach} from 'vitest';
import {createPdfExportUi} from '../../../../src/pdf/export-ui';
import {createCommandStore} from '../../../../src/document/command-store';
const writer=vi.hoisted(()=>({build:vi.fn()}));
vi.mock('../../../../src/pdf/pdf-export',()=>({buildPdfExport:writer.build}));
vi.mock('../../../../src/pdf/assets',()=>({loadBundledPdfAssets:()=>({})}));
function fixture():any{return {format:'freeform',formatVersion:'1.0.0',show:{id:'review',title:'Fresh review',totalCounts:32},field:{preset:'NFHS_11_PLAYER',unitsPerYard:2880,lengthUnits:288000,widthUnits:153600,frontHashY:51200,backHashY:102400},settings:{collisionThresholdUnits:2880},performers:[{id:'p',rankCode:'P',displayName:'Fresh'}],sets:[0,16,32].map((n,i)=>({id:`s${i}`,name:`Set ${i}`,startCount:n,positions:{p:{x:28800,y:28800}}})),transitions:[{id:'t',fromSetId:'s0',toSetId:'s1',counts:16,mode:'float'}],annotations:[]};}
const q=(id:string)=>document.getElementById(id)!;
const change=(id:string,value?:string)=>{const c=q(id) as HTMLInputElement;if(value!==undefined)c.value=value;c.dispatchEvent(new Event('change',{bubbles:true}));};
const input=(v:string)=>{const c=q('pdf-export-counts-t') as HTMLInputElement;c.value=v;c.dispatchEvent(new Event('input',{bubbles:true}));};
const submit=()=>document.querySelector('form')!.dispatchEvent(new Event('submit',{cancelable:true,bubbles:true}));
const ready=()=>({ok:true,bytes:new Uint8Array([1,2]),filename:'Fresh.pdf',manifest:{pages:[]},warnings:[]});
function setup(){const store=createCommandStore(fixture());const ui=createPdfExportUi(store);document.body.append(ui.render());q('pdf-export-invoke').focus();q('pdf-export-invoke').click();return {store,ui};}
afterEach(()=>{document.body.replaceChildren();vi.restoreAllMocks();vi.unstubAllGlobals();writer.build.mockReset();});
it('F1 concrete count copy and first invalid focus',async()=>{setup();await Promise.resolve();q('pdf-export-transition-t').focus();change('pdf-export-transition-t');await Promise.resolve();for(const [v,msg] of [['1.5',"1.5 isn't a whole number."],['-08',"-08 can't be negative."],['17',"17 isn't a valid count"],['08,8','8 is listed more than once.']]){input(v);q('pdf-export-submit').focus();submit();await Promise.resolve();expect(q('pdf-export-field-error').textContent).toContain(msg);expect(document.activeElement).toBe(q('pdf-export-counts-t'));}expect(writer.build).not.toHaveBeenCalled();});
it('F2 radio redraw restores target; status identity stable',async()=>{setup();const status=q('pdf-export-status');q('pdf-export-packet').focus();change('pdf-export-packet');await Promise.resolve();expect(document.activeElement).toBe(q('pdf-export-packet'));expect(q('pdf-export-status')).toBe(status);});
it('F2 diagnostic: Select all redraw still loses inside focus',async()=>{setup();change('pdf-export-packet');await Promise.resolve();const b=[...document.querySelectorAll('button')].find(n=>n.textContent==='Select all')!;b.focus();b.click();await Promise.resolve();console.log('select-all-focus',document.activeElement?.tagName,document.activeElement?.id);expect(document.activeElement).toBe(document.body);});
it('F2 diagnostic: summary redraw still loses inside focus',async()=>{const {ui}=setup();writer.build.mockResolvedValue({...ready(),warnings:[{code:'note-overlap',pageIndex:0,performerId:'p',annotationId:'n',obstacleKind:'dot',context:{kind:'static-set',setId:'s0'},noteBounds:{x:1,y:1,width:2,height:2},obstacleBounds:{x:1,y:1,width:2,height:2}}],manifest:{pages:[{kind:'director'}]}});submit();await vi.waitFor(()=>expect(q('pdf-export-download')).not.toBeNull());const summary=document.querySelector('summary')!;summary.tabIndex=0;summary.focus();ui.render();await Promise.resolve();expect(document.activeElement).toBe(document.body);});
it('F3 narrowed range rejects retained explicit request',async()=>{setup();change('pdf-export-transition-t');input('0,8,16');change('pdf-export-range');change('pdf-export-first-set','s0');change('pdf-export-last-set','s0');q('pdf-export-submit').focus();submit();await Promise.resolve();expect(q('pdf-export-field-error').textContent).toContain("This transition isn't fully inside");expect(writer.build).not.toHaveBeenCalled();expect(document.activeElement).toBe(q('pdf-export-transitions'));});
it('F4 same bytes retry without rerun',async()=>{const {store}=setup();const before=store.getState();writer.build.mockResolvedValue(ready());q('pdf-export-submit').focus();submit();await vi.waitFor(()=>expect(q('pdf-export-download')).not.toBeNull());vi.stubGlobal('URL',{createObjectURL:()=>{throw Error('simulated');},revokeObjectURL:vi.fn()});q('pdf-export-download').focus();q('pdf-export-download').click();await Promise.resolve();expect(document.activeElement).toBe(q('pdf-export-status'));expect(q('pdf-export-download')).not.toBeNull();const blob=vi.fn(()=> 'blob:retry');vi.stubGlobal('URL',{createObjectURL:blob,revokeObjectURL:vi.fn()});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});q('pdf-export-download').click();expect(writer.build).toHaveBeenCalledOnce();expect(blob).toHaveBeenCalledOnce();expect(store.getState()).toBe(before);});
it('F5 pending edit close retains frozen labels no outside steal',async()=>{const {store}=setup();let resolve:any;writer.build.mockImplementation(()=>new Promise(r=>resolve=r));q('pdf-export-submit').focus();submit();await vi.waitFor(()=>expect(resolve).toBeTypeOf('function'));const captured=writer.build.mock.calls[0][0];store.apply({type:'document.replace',document:{...store.getState().document,sets:store.getState().document.sets.map(s=>({...s,name:'Changed after capture'}))}});q('pdf-export-close').focus();q('pdf-export-close').click();await Promise.resolve();const outside=document.createElement('button');document.body.append(outside);outside.focus();resolve({...ready(),warnings:[{code:'note-overlap',pageIndex:0,performerId:'p',annotationId:'n',obstacleKind:'dot',context:{kind:'static-set',setId:'s0'},noteBounds:{x:1,y:1,width:2,height:2},obstacleBounds:{x:1,y:1,width:2,height:2}}],manifest:{pages:[{kind:'director'}]}});await new Promise(r=>setTimeout(r,30));expect(document.activeElement).toBe(outside);expect(document.querySelector('#pdf-export-download')).toBeNull();q('pdf-export-invoke').focus();q('pdf-export-invoke').click();await Promise.resolve();expect(document.querySelector('.pdf-export-warnings')!.textContent).toContain('Set Set 0');expect(document.querySelector('.pdf-export-warnings')!.textContent).not.toContain('Changed after capture');expect(captured.sets[0].name).toBe('Set 0');expect(store.getState().document.sets[0].name).toBe('Changed after capture');});
it('writer simulated failure preserves state focuses status',async()=>{const {store}=setup();const before=store.getState();writer.build.mockRejectedValue(Error('simulated writer'));q('pdf-export-submit').focus();submit();await vi.waitFor(()=>expect(q('pdf-export-status').textContent).toContain('problem building'));expect(document.activeElement).toBe(q('pdf-export-status'));expect(store.getState()).toBe(before);});
