import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';

const out = 'evidence/m8-ui/wheeljack-retest';
const chrome = '/Users/jatiller/Library/Caches/ms-playwright/chromium-1208/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const profile = `${process.env.TMPDIR}/m8-wheeljack-browser-${process.pid}`;
const proc = spawn(chrome, ['--headless=new', '--remote-debugging-port=0', '--no-first-run', `--user-data-dir=${profile}`, 'about:blank']);
let stderr = '';
try {
  const stage = async (value) => writeFile(`${out}/stage.txt`, `${value}\n`);
  await mkdir(out, { recursive: true });
  await stage('launching chrome');
  const endpoint = await new Promise((resolve, reject) => {
    proc.stderr.on('data', (bytes) => { stderr += bytes; const match = stderr.match(/DevTools listening on (ws:\/\/[^\s]+)/); if (match) resolve(match[1]); });
    proc.once('exit', (code) => reject(new Error(`Chrome exited ${code}`)));
    setTimeout(() => reject(new Error('Chrome endpoint timeout')), 20_000).unref();
  });
  const socket = new WebSocket(endpoint);
  await stage('chrome endpoint ready');
  await new Promise((resolve) => socket.addEventListener('open', resolve, { once: true }));
  let sequence = 0;
  const waiting = new Map();
  const events = [];
  socket.addEventListener('message', (event) => { const message = JSON.parse(event.data); if (message.id) { const pending = waiting.get(message.id); waiting.delete(message.id); message.error ? pending.reject(new Error(JSON.stringify(message.error))) : pending.resolve(message.result); } else events.push(message); });
  const call = (method, params = {}, sessionId) => new Promise((resolve, reject) => { const id = ++sequence; waiting.set(id, { resolve, reject }); socket.send(JSON.stringify({ id, method, params, ...(sessionId ? { sessionId } : {}) })); });
  const version = await call('Browser.getVersion');
  const { targetId } = await call('Target.createTarget', { url: 'about:blank' });
  const { sessionId } = await call('Target.attachToTarget', { targetId, flatten: true });
  const c = (method, params = {}) => call(method, params, sessionId);
  const evaluate = async (expression) => { const result = await c('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails)); return result.result.value; };
  await c('Page.enable'); await c('Runtime.enable'); await c('Network.enable');
  await c('Page.navigate', { url: 'http://127.0.0.1:5173/' });
  await stage('navigated');
  for (let i = 0; i < 100 && !await evaluate('Boolean(document.querySelector("form"))'); i += 1) await new Promise((resolve) => setTimeout(resolve, 50));
  await evaluate(`(()=>{for(const [id,value] of [['setup-title','M8 UI retest'],['setup-instrument-1','Trumpet'],['setup-prefix-1','T'],['setup-count-1','2']]){const node=document.getElementById(id);node.value=value;node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));}document.querySelector('form').requestSubmit();})()`);
  await stage('wizard submitted');
  const click = async (selector) => { const point = await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`); await c('Input.dispatchMouseEvent', { type: 'mousePressed', ...point, button: 'left', clickCount: 1 }); await c('Input.dispatchMouseEvent', { type: 'mouseReleased', ...point, button: 'left', clickCount: 1 }); };
  const button = (label) => evaluate(`(()=>{[...document.querySelectorAll('button')].find((node)=>node.textContent===${JSON.stringify(label)}).click();})()`);
  const ready = async () => { for (let i = 0; i < 600; i += 1) { if (await evaluate('Boolean(document.querySelector("#pdf-export-download"))')) return; await new Promise((resolve) => setTimeout(resolve, 50)); } throw new Error('PDF readiness timeout'); };
  await button('Create fully covered set'); await button('Create float transition');
  await stage('editor fixture ready');
  await c('Emulation.setDeviceMetricsOverride', { width: 1280, height: 2400, deviceScaleFactor: 1, mobile: false });
  await mkdir(`${out}/downloads`, { recursive: true });
  await call('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: `${process.cwd()}/${out}/downloads`, eventsEnabled: true });
  const findings = [];
  await click('#pdf-export-invoke');
  await evaluate('document.querySelector("#pdf-export-director").focus()'); await click('#pdf-export-director');
  findings.push({ case: 'director-radio-focus', focus: await evaluate('document.activeElement.id') });
  await click('[id^="pdf-export-transition-"]');
  await evaluate(`(()=>{const node=document.querySelector('[id^="pdf-export-counts-"]');node.value='0,8,16';node.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  const directorStartedAt = performance.now();
  await click('#pdf-export-submit'); await ready();
  await stage('director ready');
  findings.push({ case: 'director-ready-focus', durationMs: Math.round(performance.now() - directorStartedAt), focus: await evaluate('document.activeElement.id'), download: await evaluate('document.querySelector("#pdf-export-download").textContent') });
  await click('#pdf-export-download');
  await click('#pdf-export-packet'); await click('[id^="pdf-export-performer-"]'); await click('#pdf-export-submit'); await ready(); await click('#pdf-export-download');
  await stage('packet downloaded');
  await evaluate('globalThis.__m8CreateObjectURL=URL.createObjectURL;URL.createObjectURL=()=>{throw new Error("simulated URL failure")};'); await click('#pdf-export-download');
  findings.push({ case: 'simulated-url-failure-retains-ready-bytes', retry: await evaluate('Boolean(document.querySelector("#pdf-export-download"))'), status: await evaluate('document.querySelector("#pdf-export-status").textContent') });
  await evaluate('URL.createObjectURL=globalThis.__m8CreateObjectURL'); await click('#pdf-export-download');
  await stage('retry downloaded');
  await c('Network.emulateNetworkConditions', { offline: true, latency: 0, downloadThroughput: 0, uploadThroughput: 0 });
  const offlineStartedAt = performance.now();
  await click('#pdf-export-submit'); await ready();
  findings.push({ case: 'offline-after-writer-assets-loaded', durationMs: Math.round(performance.now() - offlineStartedAt), ready: await evaluate('Boolean(document.querySelector("#pdf-export-download"))'), status: await evaluate('document.querySelector("#pdf-export-status").textContent') });
  await c('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: -1, uploadThroughput: -1 });
  await click('#pdf-export-invoke');
  await click('#pdf-export-range'); await evaluate("document.querySelector('#pdf-export-first-set').value='set-1';document.querySelector('#pdf-export-first-set').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('#pdf-export-last-set').value='set-1';document.querySelector('#pdf-export-last-set').dispatchEvent(new Event('change',{bubbles:true}));");
  await click('#pdf-export-submit'); await ready();
  findings.push({ case: 'inclusive-range-single-set', ready: await evaluate('Boolean(document.querySelector("#pdf-export-download"))'), download: await evaluate('document.querySelector("#pdf-export-download").textContent') });
  await click('#pdf-export-close');
  await click('#pdf-export-invoke'); await click('#pdf-export-packet');
  await evaluate(`(()=>{const boxes=[...document.querySelectorAll('[id^="pdf-export-performer-"]')];boxes[0].click();})()`);
  await click('#pdf-export-submit'); await ready();
  const packetFilename = await evaluate('document.querySelector("#pdf-export-download").textContent');
  await click('#pdf-export-download');
  findings.push({ case: 'single-performer-packet-filtering', download: packetFilename });
  await new Promise((resolve) => setTimeout(resolve, 750));
  const network = events.filter((event) => event.method?.startsWith('Network.')).map((event) => ({ method: event.method, url: event.params?.request?.url ?? event.params?.response?.url }));
  const consoleEvents = events.filter((event) => event.method === 'Runtime.consoleAPICalled');
  await writeFile(`${out}/runtime.json`, `${JSON.stringify({ version, findings, network, consoleCount: consoleEvents.length }, null, 2)}\n`);
  await writeFile(`${out}/events.json`, `${JSON.stringify(events, null, 2)}\n`);
  console.log(JSON.stringify({ version, findings, downloads: `${out}/downloads` }, null, 2));
  socket.close();
} finally {
  proc.kill();
  await mkdir(out, { recursive: true });
  await writeFile(`${out}/chrome-stderr.log`, stderr);
}
